import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import * as THREE from 'three';
import {makeBoat} from '../src/boat.js';
import {makeCharacter} from '../src/characters.js';
import {Animator,lookAngles,LOOK_LIMIT} from '../src/animation.js';
import {makeFish,SPECIES,flop} from '../src/fish.js';
import {Ragdolls} from '../src/physics.js';
const ctx={window:{}};vm.runInNewContext(fs.readFileSync('public/assets/modelos.js','utf8'),ctx);const data=ctx.window.PESCA,assets={data,materials:data.materials.map(()=>new THREE.MeshStandardMaterial()),faces:[new THREE.Texture(),new THREE.Texture()],averages:[new THREE.Vector3(.5,.3,.25),new THREE.Vector3(.5,.4,.35)]};
test('Barco agrupa centenas de peças em menos de vinte chamadas',()=>{const boat=makeBoat(assets);let meshes=0;boat.traverse(n=>{if(n.isMesh)meshes++;});assert.ok(meshes<20,`Esperado menos de 20, obtido ${meshes}`);let tris=0;boat.traverse(n=>{if(n.isMesh)tris+=n.geometry.attributes.position.count/3;});assert.ok(tris>8000,`casco detalhado: ${tris}`);});
test('Dois personagens com foto, juntas e animação procedural de passada e tapa',()=>{for(let i=0;i<2;i++){const c=makeCharacter(assets,i);assert.equal(Object.keys(c.userData.joints).length,10);const face=c.getObjectByName('Rosto fotografico');assert.ok(face.material.userData.face.map);assert.ok(face.geometry.attributes.normal);assert.equal(face.parent,c.userData.joints.head);
  const a=new Animator(c);for(let k=0;k<30;k++)a.update(1/60,{time:k/60,speed:1.5,grounded:true});assert.notEqual(c.userData.joints.thighL.rotation.x,0);
  a.update(1/60,{time:1,slap:.5,grounded:true});assert.notEqual(c.userData.joints.armL.rotation.y,0);a.update(1/60,{time:1,embrace:1,kiss:1,grounded:true});assert.notEqual(c.userData.joints.head.rotation.z,0);
  let tris=0;c.traverse(o=>{if(o.isMesh)tris+=o.geometry.attributes.position.count/3;});assert.ok(tris>2500,`personagem detalhado: ${tris} triângulos`);}});
test('Cabeças se olham só dentro do cone frontal e com trava de 60 graus',()=>{const a={x:0,y:1.6,z:0};assert.equal(lookAngles(a,0,{x:0,y:1.6,z:-1}),null);const side=lookAngles(a,0,{x:1,y:1.6,z:.4});assert.ok(side&&Math.abs(side.yaw)<=LOOK_LIMIT+1e-9);const front=lookAngles(a,0,{x:.2,y:1.6,z:1});assert.ok(front.yaw>0&&front.yaw<.3);});
test('Peixes de todas as espécies se debatem',()=>{for(let i=0;i<SPECIES.length;i++){const f=makeFish(i);flop(f,.1,1);assert.ok(f.userData.mat.userData.uniforms.uFlop.value===1);}});
test('Ragdoll articulado recebe impulso ao tocar a água e limpa os corpos',()=>{const scene=new THREE.Scene(),rig=makeCharacter(assets,0);scene.add(rig);rig.position.set(5,-2,0);scene.updateMatrixWorld(true);const r=new Ragdolls(scene);r.launch(0,rig,[1,0,0]);let launched=false;r.update(1/60,()=>0,()=>launched=true);assert.equal(launched,true);assert.ok(r.active.get(0).bodies.torso.velocity.y>10);assert.equal(r.active.get(0).constraints.length,9);for(let i=0;i<180;i++)r.update(1/60,()=>0,()=>{});for(const b of Object.values(r.active.get(0).bodies))assert.ok(Number.isFinite(b.position.y));const snapshot=r.snapshot();assert.equal(snapshot[0].id,0);r.remove(0);assert.equal(r.active.size,0);assert.equal(r.world.bodies.length,1);assert.equal(rig.visible,true);});
test('GLBs contêm textura PNG incorporada e coordenadas UV válidas',()=>{for(const name of ['personagem-01','personagem-02']){const b=fs.readFileSync(`public/assets/${name}.glb`);assert.equal(b.readUInt32LE(0),0x46546c67);assert.equal(b.readUInt32LE(8),b.length);const n=b.readUInt32LE(12),doc=JSON.parse(b.subarray(20,20+n));assert.equal(doc.images[0].mimeType,'image/png');assert.ok(doc.meshes.at(-1).primitives[0].attributes.TEXCOORD_0>=0);const view=doc.bufferViews[doc.images[0].bufferView],png=b.subarray(28+n+view.byteOffset);assert.equal(png[0],137);assert.equal(png.subarray(1,4).toString(),'PNG');}});
