import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {loadAssets} from './models.js';
import {makeCharacter} from './characters.js';
import {makeBoat,addHelm,addMotor,addLantern} from './boat.js';
import {Animator} from './animation.js';
const canvas=document.querySelector('canvas'),stage=document.querySelector('#stage'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x10272c);scene.add(new THREE.HemisphereLight(0xffe4bb,0x355265,2.5));const sun=new THREE.DirectionalLight(0xffd9a4,3);sun.position.set(-3,5,4);scene.add(sun);const camera=new THREE.PerspectiveCamera(42,1,.05,100),controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.minDistance=.8;controls.maxDistance=25;
const assets=await loadAssets(),models=[0,1,2,3].map(i=>makeCharacter(assets,i)).concat([(()=>{const g=new THREE.Group();g.add(makeBoat());addHelm(g);addMotor(g);addLantern(g);return g;})()]);const anims=models.slice(0,4).map(m=>new Animator(m));models.forEach(m=>scene.add(m));let selected=0,wire=false;
function choose(i){selected=i;models.forEach((m,k)=>m.visible=i===k);controls.target.set(0,i===4?.65:.96,0);camera.position.set(i===4?6:1,i===4?6.2:1.75,i===4?10:3.6);controls.update();document.querySelectorAll('[data-model]').forEach((b,k)=>b.classList.toggle('active',i===k));}
document.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.model)));document.querySelector('#front').onclick=()=>{camera.position.set(0,selected===4?7:1,selected===4?9:3.8);controls.update()};document.querySelector('#back').onclick=()=>{camera.position.set(0,selected===4?7:1,selected===4?-9:-3.8);controls.update()};document.querySelector('#wire').onclick=()=>{wire=!wire;models.forEach(m=>m.traverse(o=>{if(o.isMesh)o.material.wireframe=wire;}));};document.querySelector('#reset').onclick=()=>choose(selected);
function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(stage);resize();choose(0);let frame=0;const clock=new THREE.Clock();let time=0;function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);time+=dt;anims.forEach(a=>a.update(dt,{time,grounded:true}));controls.update();renderer.render(scene,camera);if(++frame%30===0)document.querySelector('#stats').textContent=`WEBGL · ${renderer.info.render.calls} chamadas de desenho · ${renderer.info.render.triangles.toLocaleString('pt-BR')} triângulos`;}animate();

// Exporta o modelo atual (já com a foto no rosto) em GLB, direto do navegador.
document.querySelector('#download').addEventListener('click',e=>{e.preventDefault();const names=['personagem-01','personagem-02','personagem-03','personagem-04','barco-de-pesca'];new GLTFExporter().parse(models[selected],glb=>{const url=URL.createObjectURL(new Blob([glb],{type:'model/gltf-binary'}));const a=document.createElement('a');a.href=url;a.download=names[selected]+'.glb';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);},err=>console.error(err),{binary:true});});
