// Proposed gameplay only: this collection is deliberately not wired to purchases,
// inventory, damage or economy until those systems are designed and balanced.
export const STORE_CATEGORIES=['Pesca de precisão','Navegação e pesquisa','Oficina de bordo','Expedição e sobrevivência','Iscas e caçada'];
const entries=[
  ['rod','Vara Maré Negra','Blank de carbono, passadores cerâmicos e cabo de cortiça.','Amplia a distância de arremesso e tolera peixes pesados.','Ponteira flexível'],
  ['reel','Carretilha Leviatã','Carretel ventilado, manivela dupla e freio micrométrico.','Recolhe a linha mais rápido; o freio reduz rompimentos.','Carretel e manivela'],
  ['harpoon','Arpão de contenção','Lançador pneumático com carreto, arpão farpado e manômetro.','Prende temporariamente um alvo grande ao barco.','Alavanca de armação'],
  ['net','Passaguá telescópico','Aro assimétrico, rede com nós e haste extensível.','Retira peixes pequenos e médios sem gastar a linha.','Trava de extensão'],
  ['gaff','Bicheiro de convés','Gancho recurvo com ponta afiada, guarda e empunhadura enrolada.','Ajuda a embarcar pescados pesados próximos ao casco.','Guarda da ponta'],
  ['knife','Faca de filetagem','Lâmina curva de aço, espiga aparente e cabo de madeira rebitado.','Transforma pescados em provisões e iscas de corte.','Bainha articulada'],
  ['pliers','Alicate de anzol','Mandíbulas serrilhadas, mola de retorno e cabos emborrachados.','Remove anzóis e recupera parte dos acessórios.','Mandíbulas'],
  ['tackle','Maleta de pesca','Estojo vedado com dobradiças, bandejas e divisórias equipadas.','Adiciona espaço dedicado a anzóis, boias e iscas.','Tampa e fechos'],
  ['line','Carretel de fluorcarbono','Bobina raiada, linha enrolada e guia cerâmico.','Reduz a percepção da linha por espécies ariscas.','Guia distribuidor'],
  ['scale','Balança de cais','Dinamômetro de latão com mostrador, ponteiro e gancho.','Revela peso e valor estimado de cada captura.','Ponteiro de carga'],
  ['sonar','Sonar de varredura','Visor em relevo, botões selados, suporte e cabo de transdutor.','Mostra cardumes e silhuetas grandes sob a embarcação.','Varredura do visor'],
  ['compass','Bússola de capitão','Caixa de latão, rosa dos ventos, agulha e tampa gravada.','Mantém a orientação durante neblina e tempestades.','Agulha magnética'],
  ['sextant','Sextante de bronze','Arco graduado, braço de índice, espelhos e ocular.','Permite marcar pontos de interesse distantes.','Braço de índice'],
  ['scope','Luneta de vigia','Tubos de latão extensíveis, lentes e anéis serrilhados.','Identifica perigos e pontos de pesca antes da aproximação.','Tampa da objetiva'],
  ['radio','Rádio de ondas curtas','Carcaça blindada, grelha de alto-falante, antena e seletores.','Recebe avisos de clima e pistas de eventos do lago.','Seletor de frequência'],
  ['beacon','Boia sinalizadora','Flutuador com quilha, torre luminosa e olhal de amarração.','Marca um local para encontrá-lo novamente à noite.','Refletor giratório'],
  ['depth','Sonda mecânica','Tambor graduado, cabo de aço e peso hidrodinâmico.','Mede a profundidade para escolher a montagem da linha.','Tambor de cabo'],
  ['chart','Carta náutica impermeável','Pergaminho dobrado, relevo cartográfico e presilhas de metal.','Registra rotas seguras e locais já explorados.','Régua de navegação'],
  ['barometer','Barômetro de tempestade','Instrumento de parede com aro torneado e escala dupla.','Antecipa mudanças de clima para planejar a viagem.','Ponteiro de pressão'],
  ['camera','Câmera de pesquisa','Câmera estanque com objetiva, visor, disparador e correia.','Documenta espécies e evidências de criaturas lendárias.','Obturador externo'],
  ['anchor','Âncora de almirantado','Haste forjada, cepo transversal e unhas com arestas gastas.','Estabiliza o barco durante a pesca em água profunda.','Manilha superior'],
  ['winch','Guincho de convés','Tambor de cabo, engrenagens, catraca e base aparafusada.','Recolhe âncoras e cargas que não podem ser erguidas à mão.','Tambor e manivela'],
  ['motor','Motor Rabeta-40','Capota ventilada, bloco inferior, hélice e manche de direção.','Aumenta a velocidade do barco com consumo de combustível.','Hélice e comando'],
  ['propeller','Hélice antialgas','Três pás torcidas com bordas afiladas e cubo estriado.','Melhora o desempenho em vegetação aquática.','Rotor de três pás'],
  ['rudder','Leme de emergência','Pá de madeira laminada, ferragens e cana de comando.','Permite manobrar quando o motor fica inutilizado.','Cana do leme'],
  ['pump','Bomba de porão','Corpo fundido, volante, mangueiras corrugadas e filtro.','Retira água acumulada após impactos e tempestades.','Volante da bomba'],
  ['battery','Bateria náutica','Caixa vedada, bornes protegidos, alça e cabos de cobre.','Alimenta sonar, rádio e iluminação por mais tempo.','Alça dobrável'],
  ['repair','Kit de reparos','Caixa de ferramentas com chave, rolos de vedação e ferragens.','Restaura parte da resistência do casco fora de combate.','Tampa da caixa'],
  ['fuel','Galão de reserva','Reservatório prensado com nervuras, bocal e trava de segurança.','Reabastece o motor durante expedições longas.','Tampa com trava'],
  ['drogue','Âncora de deriva','Cone de lona costurado, boca reforçada e cabos de tração.','Diminui a deriva enquanto mantém o barco alinhado às ondas.','Manilha de tração'],
  ['lantern','Lampião de convés','Estrutura de latão, vidro protegido, pavio e alça de transporte.','Ilumina o barco e atrai pequenos peixes durante a noite.','Alça de suspensão'],
  ['torch','Lanterna de mergulho','Corpo estriado, refletor profundo e proteção de borracha.','Ilumina objetos e ameaças debaixo d’água.','Aro de foco'],
  ['flask','Garrafa térmica','Corpo de aço escovado, tampa dosadora e alça de couro.','Mantém bebidas que recuperam fôlego durante o frio.','Tampa rosqueada'],
  ['stove','Fogareiro de campanha','Queimador, grelha dobrável, tanque pressurizado e válvula.','Cozinha pescados para produzir refeições melhores.','Registro de gás'],
  ['medkit','Maleta de primeiros socorros','Estojo com cruz em relevo, bandagens, tesoura e frascos.','Recupera saúde e trata ferimentos longe do cais.','Tampa do estojo'],
  ['vest','Colete salva-vidas','Painéis de espuma, tecido costurado, fivelas e apito preso.','Aumenta o tempo de sobrevivência após cair na água.','Fivela de engate'],
  ['oxygen','Cilindro de mergulho','Cilindro, válvula dupla, regulador, manômetro e mangueira.','Amplia o tempo de exploração submersa.','Volante da válvula'],
  ['fins','Nadadeiras de exploração','Par de palas com nervuras, botas anatômicas e tiras de calcanhar.','Aumenta a velocidade de nado sob a superfície.','Tira de calcanhar'],
  ['pack','Mochila estanque','Lona dobrada, fecho enrolado, bolsos e tiras ajustáveis.','Protege provisões e adiciona capacidade de transporte.','Fecho superior'],
  ['tent','Abrigo de margem','Lona tensionada, varetas cruzadas, estacas e entrada dobrável.','Permite descansar em margens seguras durante expedições.','Aba da entrada'],
  ['lure','Isca peixe articulado','Corpo em três segmentos, escamas gravadas, olhos e garateias.','Imita um peixe ferido e atrai predadores grandes.','Cauda articulada'],
  ['frog','Isca rã de superfície','Corpo macio, olhos altos, patas dobradas e anzol duplo.','Atrai predadores escondidos entre plantas aquáticas.','Patas traseiras'],
  ['shrimp','Camarão de profundidade','Carapaça segmentada, antenas, patas e cauda em leque.','Atrai espécies de fundo e permite pesca rente às pedras.','Cauda segmentada'],
  ['spinner','Spinner de cobre','Colher martelada, girador, contas e anzol com penacho.','Produz reflexos e vibrações em água turva.','Colher rotativa'],
  ['chum','Cesto de ceva','Cesto perfurado com tampa, chumbo e fragmentos de alimento.','Mantém cardumes próximos por um período limitado.','Tampa do cesto'],
  ['rattle','Chocalho abissal','Câmara acústica com contrapesos, grelha e anéis de suspensão.','Atrai criaturas sensíveis a vibrações de longa distância.','Rotor acústico'],
  ['decoy','Chamariz de presa','Peixe mecânico flutuante com cauda de palheta e chave de corda.','Desvia a atenção de uma criatura enquanto o barco recua.','Cauda oscilante'],
  ['hydrophone','Hidrofone de caçada','Microfone submersível, gaiola de proteção e receptor com cabo.','Ajuda a localizar o rugido subaquático de um boss.','Sintonia do receptor'],
  ['flare','Sinalizador de emergência','Lançador com culatra basculante, cartucho e empunhadura de madeira.','Revela a posição do barco e ilumina ameaças à distância.','Culatra basculante'],
  ['trap','Armadilha de lagosta','Armação arqueada, entrada em funil, cordame e portinhola.','Captura crustáceos passivamente quando deixada no fundo.','Portinhola de coleta'],
];
export const STORE_ITEMS=entries.map(([id,name,description,effect,motion],i)=>({id,name,description,effect,motion,category:STORE_CATEGORIES[Math.floor(i/10)],number:i+1,status:'Conceito · efeito ainda não implementado'}));
